---
title: "Title of the project"
author: "Your Name or Nickname"
date: "2025-07-08"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Report the most important findings and discuss the results.** References to the papers should be provided in `references.bib` file, which is linked to this document (see the header in `Rmd` file). You cite the papers like [@liu2015m6a]. In this case reference will automatically appear in your `References` section at the end of the report. In order to get citations already in the desired format for `references.bib` file, go to Google Scholar, find the article, click on `Cite` and select `BibTeX`. Copy the citation an paste it in `references.bib`

## Topic of the research project

## Introduction

Here I am writing the introduction to my topic and cite the relevant papers.

## Dataset

Describe your dataset

## Methods

- describe differential gene expression
- describe pathway analysis 

## Results

In this section your concrete results should be described. Include the most important figures and tables.

## Discussion and Outlook

Here you should discuss all results you have got over the course. Put the results into a broader picture and give some future outlook.

## References 


